
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Titouan HETMANIAK
 */
public class FENETRE_QUIZ extends javax.swing.JFrame {

    private ArrayList<Question> questions;
    private int indexQuestionCourante = 0;
    private int score = 0;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FENETRE_QUIZ.class.getName());

    /**
     * Creates new form FENETRE_QUIZ
     */
    public FENETRE_QUIZ() {
        initComponents();

    questions = new ArrayList<>();

    questions.add(new Question(
            "Quel est le plus grand océan du monde ?",
            "Atlantique", "Indien", "Arctique", "Pacifique", 4));

    questions.add(new Question(
            "Combien font 7 × 8 ?",
            "54", "56", "64", "48", 2));

    questions.add(new Question(
            "Qui a inventé Java ?",
            "Microsoft", "Sun Microsystems", "IBM", "Oracle", 2));

    questions.add(new Question(
            "Quelle est la capitale de l'Australie ?",
            "Sydney", "Melbourne", "Perth", "Canberra", 4));

    questions.add(new Question(
            "Quel est le meilleur prof de l'EPF ?",
            "B.DARTIES", "ABDELLA", "JOUSSET", "DURAND", 1));

    afficherQuestionCourante();
}

    private void afficherQuestionCourante() {
    Question q = questions.get(indexQuestionCourante);

    lblQuestion.setText(q.getIntitule());
    btnRep1.setText(q.getProposition1());
    btnRep2.setText(q.getProposition2());
    btnRep3.setText(q.getProposition3());
    btnRep4.setText(q.getProposition4());

    lblFeedback.setText("");
    lblScore.setText("Score : " + score);

    btnRep1.setEnabled(true);
    btnRep2.setEnabled(true);
    btnRep3.setEnabled(true);
    btnRep4.setEnabled(true);
}

    private void verifierReponse(int choix) {
    Question q = questions.get(indexQuestionCourante);

    if (choix == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse !");
        score++;
        lblScore.setText("Score : " + score);
    } else {
        lblFeedback.setText("Mauvaise réponse...");
    }

    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuestion.setText("jLabel1");

        btnRep1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRep2.setText("jButton1");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRep3.setText("jButton1");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRep4.setText("jButton1");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblFeedback.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblFeedback.setText("jLabel1");

        btnSuivant.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSuivant.setText("SUIVANT");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblScore.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFeedback)
                        .addGap(179, 179, 179)
                        .addComponent(lblScore))
                    .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRep3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnRep1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btnRep2)
                        .addGap(34, 34, 34)
                        .addComponent(btnRep4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btnSuivant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblFeedback)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2)
                    .addComponent(btnRep4))
                .addGap(32, 32, 32)
                .addComponent(btnSuivant)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        indexQuestionCourante++;

    if (indexQuestionCourante < questions.size()) {
        afficherQuestionCourante();
    } else {
        lblQuestion.setText("Quiz terminé !");
        lblFeedback.setText("BIEN JOUE : Score final : " + score + " / " + questions.size());

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        btnSuivant.setEnabled(false);
    }


    }//GEN-LAST:event_btnSuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FENETRE_QUIZ().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

    private void VerifierReponse(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}