/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Titouan HETMANIAK
 */
public class FenetreCadenas extends javax.swing.JFrame {
        private CadenasGame jeu;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreCadenas.class.getName());

    /**
     * Creates new form FenetreCadenas
     */
    public FenetreCadenas() {
        initComponents();
                
        this.jeu = new CadenasGame(4, 5); // 4 chiffres, 5 tentatives
        initialiserAffichage();
    }
    
            private void initialiserAffichage() {
        // Tous les chiffres à 0 au début
        lblDigit1.setText("0");
        lblDigit2.setText("0");
        lblDigit3.setText("0");
        lblDigit4.setText("0");

        lblExact.setText("0");
        lblTropHaut.setText("0");
        lblTropBas.setText("0");

        lblTentatives.setText("0 sur " + jeu.getMaxTentatives());
    }


        private void incrementerLabel(javax.swing.JLabel label) {
        int valeur = Integer.parseInt(label.getText());
        valeur = (valeur + 1) % 10; // boucle 0 -> 9 -> 0
        label.setText(Integer.toString(valeur));
    }

    private void decrementerLabel(javax.swing.JLabel label) {
        int valeur = Integer.parseInt(label.getText());
        valeur = (valeur - 1 + 10) % 10; // boucle 0 -> 9 -> 0 à l'envers
        label.setText(Integer.toString(valeur));
    }
  
        

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDigit2 = new javax.swing.JLabel();
        lblDigit1 = new javax.swing.JLabel();
        lblDigit4 = new javax.swing.JLabel();
        btnDown1 = new javax.swing.JButton();
        btnDown2 = new javax.swing.JButton();
        btnDown3 = new javax.swing.JButton();
        btnDown4 = new javax.swing.JButton();
        btnUp2 = new javax.swing.JButton();
        btnUp1 = new javax.swing.JButton();
        btnUp3 = new javax.swing.JButton();
        btnUp4 = new javax.swing.JButton();
        btnTester = new javax.swing.JButton();
        lblDigit3 = new javax.swing.JLabel();
        lblTropBas = new javax.swing.JLabel();
        lblTentatives = new javax.swing.JLabel();
        btnRecommencer = new javax.swing.JButton();
        lblTropHaut = new javax.swing.JLabel();
        lblExact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Trouvez le bon code en moins de 5 tentatives");

        lblDigit2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit2.setText("0");
        lblDigit2.setBorder(new javax.swing.border.MatteBorder(null));

        lblDigit1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit1.setText("0");
        lblDigit1.setBorder(new javax.swing.border.MatteBorder(null));

        lblDigit4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigit4.setText("0");
        lblDigit4.setBorder(new javax.swing.border.MatteBorder(null));

        btnDown1.setText("\\/");
        btnDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown1ActionPerformed(evt);
            }
        });

        btnDown2.setText("\\/");
        btnDown2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown2ActionPerformed(evt);
            }
        });

        btnDown3.setText("\\/");
        btnDown3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown3ActionPerformed(evt);
            }
        });

        btnDown4.setText("\\/");
        btnDown4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown4ActionPerformed(evt);
            }
        });

        btnUp2.setText("/\\");
            btnUp2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUp2ActionPerformed(evt);
                }
            });

            btnUp1.setText("/\\");
                btnUp1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnUp1ActionPerformed(evt);
                    }
                });

                btnUp3.setText("/\\");
                    btnUp3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnUp3ActionPerformed(evt);
                        }
                    });

                    btnUp4.setText("/\\");
                        btnUp4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUp4ActionPerformed(evt);
                            }
                        });

                        btnTester.setText("TESTER");
                        btnTester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTesterActionPerformed(evt);
                            }
                        });

                        lblDigit3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        lblDigit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        lblDigit3.setText("0");
                        lblDigit3.setBorder(new javax.swing.border.MatteBorder(null));

                        lblTropBas.setText("Nombre de chiffres trop bas : ");

                        lblTentatives.setText("Tentatives");

                        btnRecommencer.setText("RECOMMENCER");
                        btnRecommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRecommencerActionPerformed(evt);
                            }
                        });

                        lblTropHaut.setText("Nombre de chiffres trop haut : ");

                        lblExact.setText("Nombre de chiffres exacts : ");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTentatives)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnUp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDigit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnUp2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUp3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUp4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(btnTester)
                                        .addContainerGap(48, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnDown1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDown2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDown3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDown4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblExact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTropBas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTropHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRecommencer)
                                        .addGap(64, 64, 64))))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lblTentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnUp1)
                                            .addComponent(btnUp2)
                                            .addComponent(btnUp3)
                                            .addComponent(btnUp4))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTester)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDown1)
                                    .addComponent(btnDown2)
                                    .addComponent(btnDown3)
                                    .addComponent(btnDown4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblExact, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTropBas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTropHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnRecommencer)
                                        .addGap(56, 56, 56))))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void btnUp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp4ActionPerformed
        incrementerLabel(lblDigit4);
    }//GEN-LAST:event_btnUp4ActionPerformed

    private void btnUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp1ActionPerformed
         incrementerLabel(lblDigit1);
    }//GEN-LAST:event_btnUp1ActionPerformed

    private void btnDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown1ActionPerformed
        decrementerLabel(lblDigit1);
    }//GEN-LAST:event_btnDown1ActionPerformed

    private void btnUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp2ActionPerformed
         incrementerLabel(lblDigit2);
    }//GEN-LAST:event_btnUp2ActionPerformed

    private void btnUp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp3ActionPerformed
         incrementerLabel(lblDigit3);
    }//GEN-LAST:event_btnUp3ActionPerformed

    private void btnDown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown2ActionPerformed
        decrementerLabel(lblDigit2);
    }//GEN-LAST:event_btnDown2ActionPerformed

    private void btnDown3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown3ActionPerformed
        decrementerLabel(lblDigit3);
    }//GEN-LAST:event_btnDown3ActionPerformed

    private void btnDown4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown4ActionPerformed
        decrementerLabel(lblDigit4);
    }//GEN-LAST:event_btnDown4ActionPerformed

    private void btnTesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesterActionPerformed
                                                     
        int[] prop = new int[4];
        prop[0] = Integer.parseInt(lblDigit1.getText());
        prop[1] = Integer.parseInt(lblDigit2.getText());
        prop[2] = Integer.parseInt(lblDigit3.getText());
        prop[3] = Integer.parseInt(lblDigit4.getText());

        jeu.setProposition(prop);
        int[] res = jeu.evaluerProposition();

        lblExact.setText(Integer.toString(res[0]));
        lblTropHaut.setText(Integer.toString(res[1]));
        lblTropBas.setText(Integer.toString(res[2]));

        lblTentatives.setText(jeu.getNbTentatives() + " sur " + jeu.getMaxTentatives());

        // Vérifier la fin de partie
        if (res[0] == 4) { // 4 chiffres exacts
            javax.swing.JOptionPane.showMessageDialog(this, "Bravo, vous avez trouvé le code !");
            btnTester.setEnabled(false);
        } else if (jeu.isGameOver()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Perdu ! Vous avez utilisé toutes les tentatives.");
            btnTester.setEnabled(false);
        }
          

    }//GEN-LAST:event_btnTesterActionPerformed

    private void btnRecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecommencerActionPerformed
                                            
        jeu.reset();
        initialiserAffichage();
        btnTester.setEnabled(true);
      

    }//GEN-LAST:event_btnRecommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreCadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown1;
    private javax.swing.JButton btnDown2;
    private javax.swing.JButton btnDown3;
    private javax.swing.JButton btnDown4;
    private javax.swing.JButton btnRecommencer;
    private javax.swing.JButton btnTester;
    private javax.swing.JButton btnUp1;
    private javax.swing.JButton btnUp2;
    private javax.swing.JButton btnUp3;
    private javax.swing.JButton btnUp4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDigit1;
    private javax.swing.JLabel lblDigit2;
    private javax.swing.JLabel lblDigit3;
    private javax.swing.JLabel lblDigit4;
    private javax.swing.JLabel lblExact;
    private javax.swing.JLabel lblTentatives;
    private javax.swing.JLabel lblTropBas;
    private javax.swing.JLabel lblTropHaut;
    // End of variables declaration//GEN-END:variables

}